version: "3.9"

services:
  api:
    build: .
    container_name: nasa-app
    ports:
      - "8080:8080"
    restart: unless-stopped

    env_file: .env
    environment:
      # App config
      PORT: ${PORT:-8080}

      # Postgres (Heroku RDS)
      DATABASE_URL: ${DATABASE_URL}

      # OAuth & JWT
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      OAUTH_REDIRECT_URL: ${OAUTH_REDIRECT_URL}
      JWT_SECRET: ${JWT_SECRET}

      # Frontend redirect targets
      FRONTEND_URI: ${FRONTEND_URI:-http://localhost:3000}
      FRONTEND_REDIRECT_URL: ${FRONTEND_REDIRECT_URL:-http://localhost:3000/dashboard}

      # Migrations
      MIGRATE_ON_START: ${MIGRATE_ON_START:-true}

# Local PostgreSQL (ihtiyacınız varsa uncomment edin)
#  db:
#    image: postgres:15
#    container_name: nasa-db
#    restart: always
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: nasa
#    ports:
#      - "5432:5432"
#    volumes:
#      - dbdata:/var/lib/postgresql/data
#
#volumes:
#  dbdata: