version: "3.9"

services:
  api:
    build: .
    container_name: nasa-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nasa
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - APP_PORT=8080
      # Google OAuth - ÖNEMLİ: Bunları ekleyin
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - JWT_SECRET=your-super-secret-jwt-key-at-least-32-characters-long

  db:
    image: postgres:15
    container_name: nasa-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nasa
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: